name: CICD Pipeline

on: push

jobs:
  model-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: set Dagshub Mlflow credentials
        run: |
          echo "DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV
      - name: Run Pipeline
        run: |
          dvc repro
      - name: Configure DVC Authentication
        run: |
          dvc remote modify origin auth basic
          dvc remote modify origin user Iamkartikey44
          dvc remote modify origin password ${{ secrets.DAGSHUB_TOKEN }}
          
      - name: Push DVC-tracked data to remote
        run: |
          dvc push
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Add changes to Git
        run: |
          git add .
      - name: Commit changes
        if: ${{ github.actor != 'github-actions[bot]' }}
        run: |
          git commit -m "Automated commit of DVC outputs and updated code" || echo "No changes to commit"
      - name: Push changes
        if: ${{ github.actor != 'github-actions[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin ${{ github.ref_name }}
      - name: Install test dependencies
        run: |
          pip install pytest
      - name: Run model loading test
        run: |
          pytest scripts/test_load_model.py
      - name: Run model signature test
        run: |
          pytest scripts/test_model_signature.py
      - name: Run Model Performance Test
        run: |
          pytest scripts/test_model_performance.py
      - name: Promote Model to Production
        if: success()
        run: |
          python scripts/promote_model.py
      
      - name: Start Flask App
        run: |
          python flask_app/app.py > flask.log 2>&1 &
          sleep 30
      
      - name: Run Flask API Tests
        run: |
          pytest scripts/test_flask_api.py
      # Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t yt-chrome-plugin .

      # Tag image
      - name: Tag Docker image
        run: |
          docker tag yt-chrome-plugin:latest ${{ secrets.DOCKERHUB_USERNAME }}/yt-chrome-plugin:latest

      # Push image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/yt-chrome-plugin:latest
            


      




